# Generated by Django 6.0.1 on 2026-01-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zip',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
