# Generated by Django 6.0.1 on 2026-01-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_adress_zip'),
    ]

    operations = [ # instantiated a RunSQL object to write sql in this empty migration
        migrations.RunSQL(
            '''
            INSERT INTO store_collection(title)
            VALUES('collection1')
            ''',
            '''
            DELETE FROM store_collection
            WHERE title='collection1'
            '''
        )
    ]
